# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - script: |
      bash -c "sudo apt-get update && sudo apt-get install libsodium-dev libntl-dev yasm texinfo libboost-dev libboost-thread-dev python3-gmpy2 python3-networkx python3-sphinx"
  - script: |
      make mpir
  - script:
      echo USE_NTL=1 >> CONFIG.mine
  - script:
      echo MY_CFLAGS += -DFEWER_PRIMES >> CONFIG.mine
  - script:
      echo MY_CFLAGS += -DFEWER_RINGS >> CONFIG.mine
  - script:
      make
  - script:
      Scripts/setup-ssl.sh 4
  - script:
      Scripts/test_tutorial.sh -X
